; Inno Setup Script for Hopit CLI
; This script creates a professional, fast Windows installer.
; It bundles the standalone Python runtime, the Python source code, and the C# Launcher.

[Setup]
; ------------------------------
; Application Information
; ------------------------------
AppName=Hopit-cli
AppVersion=1.0.0
AppPublisher=Gnani
AppPublisherURL=https://github.com/gnani/hopit-cli
AppSupportURL=https://github.com/gnani/hopit-cli/issues
AppUpdatesURL=https://github.com/gnani/hopit-cli

; ------------------------------
; Installation Configuration
; ------------------------------
; Default installation directory (e.g., C:\Users\Username\AppData\Local\Programs\Hopit)
DefaultDirName={autopf}\Hopit
; The name of the Start Menu folder
DefaultGroupName=Hopit
; Allow the user to skip creating a Start Menu folder
AllowNoIcons=yes
; We do not need admin rights to run the installer if we install to local AppData
; If you want a machine-wide install (C:\Program Files), change this to 'admin'
PrivilegesRequired=lowest

; ------------------------------
; Application Icon Settings
; ------------------------------
; To change the icon of the Installer (.exe) itself, uncomment and edit the path below:
; (Note: Windows requires this to be a .ico file, not a .jpg or .png)
SetupIconFile=.\Images\logo.ico

; To change the icon that shows in the Windows "Add/Remove Programs" panel, 
; you can just change the icon of your C# launcher when you compile it.
UninstallDisplayIcon={app}\Hopit-cli.exe

; ------------------------------
; Output Configuration
; ------------------------------
; Where the final Setup.exe will be created
OutputDir=.\dist
; The name of the final installer file
OutputBaseFilename=Hopit_Windows_Installer

; Make the installer look modern
Compression=lzma2/ultra
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
; Checkboxes on the "Select Additional Tasks" wizard page
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; 1. The native C# Launcher (compiled earlier)
Source: ".\Hopit-cli.exe"; DestDir: "{app}"; Flags: ignoreversion

; 2. The Python Source Code
Source: ".\hopit-cli.py"; DestDir: "{app}\src"; Flags: ignoreversion
Source: ".\hopit\*"; DestDir: "{app}\src\hopit"; Flags: ignoreversion recursesubdirs createallsubdirs

; 3. The Standalone Python Runtime 
; (You must download the python-build-standalone folder into your project first)
Source: ".\python\*"; DestDir: "{app}\python"; Flags: ignoreversion recursesubdirs createallsubdirs

; Note: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
; Create a shortcut in the Start Menu pointing to the C# Launcher
Name: "{group}\Hopit"; Filename: "{app}\Hopit-cli.exe"
; (Optional) Create a shortcut for uninstalling
Name: "{group}\{cm:UninstallProgram,Hopit}"; Filename: "{uninstallexe}"
; Create a shortcut on the Desktop if the user checked the box
Name: "{autodesktop}\Hopit"; Filename: "{app}\Hopit-cli.exe"; Tasks: desktopicon

[Run]
; Option to launch the app immediately after installation finishes
Filename: "{app}\Hopit-cli.exe"; Description: "{cm:LaunchProgram,Hopit}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
; Clean up any files generated by Python at runtime (like __pycache__ or .pyc)
Type: filesandordirs; Name: "{app}\src\__pycache__"
Type: filesandordirs; Name: "{app}\src\hopit\__pycache__"
Type: filesandordirs; Name: "{app}\python\Lib\__pycache__"
